"""Generate FEMM problems from the same canonical geometry as the board.

FEMM solves 2D planar or axisymmetric problems. A planar transformer wound on
a rectangular ELP post is neither: it is a racetrack. The axisymmetric section
used here replaces the racetrack with a circle of equal turn length, which
preserves conductor length and resistance but not the field around the
straight runs and corners.

That approximation is stated in the output of every study rather than buried,
because it is the main reason a 2D leakage figure should not be treated as
final. ``unsupported_features`` enumerates exactly what the section drops.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

from .model import PlanarTransformer, Turn


@dataclass
class FemmStudy:
    """A generated FEMM problem plus what it is and is not able to say."""

    lua_path: Path
    result_path: Path
    frequency_hz: float
    equivalent_radius_m: float
    unsupported: List[str] = field(default_factory=list)
    mesh_size_mm: float = 0.0

    def caveats(self) -> str:
        return "; ".join(self.unsupported)


def unsupported_features() -> List[str]:
    """Everything the 2D axisymmetric section cannot represent."""
    return [
        "racetrack straight runs and corners, replaced by an equal-length circle",
        "plated through-hole vias and the current crowding around them",
        "termination pads and the spreading resistance into them",
        "3D flux fringing at the open sides of the ELP core",
        "conductor edge effects across the trace width",
        "interwinding capacitance, which needs an electrostatic solution",
    ]


def equivalent_radius(transformer: PlanarTransformer, turn: Turn) -> float:
    """Radius of a circle whose circumference equals the racetrack length.

    Preserving length keeps DC resistance right, which is the property the
    winding-loss comparison depends on.
    """
    return turn.length_m / (2.0 * math.pi)


def _lua_header(frequency_hz: float, depth_mm: float, precision: float) -> str:
    return (
        "-- Generated by FORGE from the canonical geometry model.\n"
        "-- Axisymmetric harmonic magnetics.\n"
        "newdocument(0)\n"
        f"mi_probdef({frequency_hz:g}, \"millimeters\", \"axi\", "
        f"{precision:g}, {depth_mm:g}, 30, 0)\n"
    )


def write_winding_study(
    transformer: PlanarTransformer,
    path: Path | str,
    frequency_hz: float,
    excitation: Dict[str, float],
    result_path: Optional[Path] = None,
    mesh_size_mm: float = 0.12,
    air_margin_mm: float = 12.0,
    core_mu_r: float = 750.0,
) -> FemmStudy:
    """Emit a Lua script solving one winding configuration.

    ``excitation`` maps winding names to amp-turns. Open-circuit and
    short-circuit variants of the same geometry give the magnetizing and
    leakage inductances respectively.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    result = Path(result_path) if result_path else path.with_suffix(".txt")

    core = transformer.core
    # Axisymmetric model: the centre post becomes a cylinder of equal area.
    post_r_mm = core.post_radius_m * 1e3
    window_h_mm = core.window_height_m * 1e3
    core_h_mm = core.height_m * 1e3
    outer_r_mm = post_r_mm + core.window_radial_m * 1e3 + 2.0
    air_r_mm = outer_r_mm + air_margin_mm
    air_z_mm = core_h_mm / 2.0 + air_margin_mm

    lines: List[str] = [_lua_header(frequency_hz, 1.0, 1e-8)]
    lines.append('mi_getmaterial("Air")')
    lines.append('mi_getmaterial("Copper")')
    lines.append(
        f'mi_addmaterial("Ferrite", {core_mu_r:g}, {core_mu_r:g}, 0, 0, 0, '
        "0, 0, 1, 0, 0, 0)"
    )

    # Circuits, one per winding, carrying the requested amp-turns.
    for winding, amps in excitation.items():
        lines.append(f'mi_addcircprop("{winding}", {amps:g}, 1)')

    # Air boundary box.
    lines.append(f"mi_addnode(0, {-air_z_mm:g})")
    lines.append(f"mi_addnode({air_r_mm:g}, {-air_z_mm:g})")
    lines.append(f"mi_addnode({air_r_mm:g}, {air_z_mm:g})")
    lines.append(f"mi_addnode(0, {air_z_mm:g})")
    lines.append(f"mi_addsegment(0, {-air_z_mm:g}, {air_r_mm:g}, {-air_z_mm:g})")
    lines.append(
        f"mi_addsegment({air_r_mm:g}, {-air_z_mm:g}, {air_r_mm:g}, {air_z_mm:g})"
    )
    lines.append(f"mi_addsegment({air_r_mm:g}, {air_z_mm:g}, 0, {air_z_mm:g})")
    lines.append(f"mi_addsegment(0, {air_z_mm:g}, 0, {-air_z_mm:g})")
    lines.append(
        'mi_addboundprop("azero", 0, 0, 0, 0, 0, 0, 0, 0, 0)'
    )
    for x, y in (
        (air_r_mm / 2, -air_z_mm), (air_r_mm, 0), (air_r_mm / 2, air_z_mm)
    ):
        lines.append(f"mi_selectsegment({x:g}, {y:g})")
    lines.append('mi_setsegmentprop("azero", 0, 1, 0, 0)')
    lines.append("mi_clearselected()")

    # Centre post and the two outer plates of the core.
    def rect(r0: float, z0: float, r1: float, z1: float) -> None:
        lines.append(f"mi_addnode({r0:g}, {z0:g})")
        lines.append(f"mi_addnode({r1:g}, {z0:g})")
        lines.append(f"mi_addnode({r1:g}, {z1:g})")
        lines.append(f"mi_addnode({r0:g}, {z1:g})")
        lines.append(f"mi_addsegment({r0:g}, {z0:g}, {r1:g}, {z0:g})")
        lines.append(f"mi_addsegment({r1:g}, {z0:g}, {r1:g}, {z1:g})")
        lines.append(f"mi_addsegment({r1:g}, {z1:g}, {r0:g}, {z1:g})")
        lines.append(f"mi_addsegment({r0:g}, {z1:g}, {r0:g}, {z0:g})")

    half_core = core_h_mm / 2.0
    plate = max((core_h_mm - 2.0 * window_h_mm) / 2.0, 0.5)
    rect(0.0, -half_core + plate, post_r_mm, half_core - plate)   # centre post
    rect(0.0, half_core - plate, outer_r_mm, half_core)            # top plate
    rect(0.0, -half_core, outer_r_mm, -half_core + plate)          # bottom plate

    for label_r, label_z in (
        (post_r_mm / 2, 0.0),
        (outer_r_mm / 2, half_core - plate / 2),
        (outer_r_mm / 2, -half_core + plate / 2),
    ):
        lines.append(f"mi_addblocklabel({label_r:g}, {label_z:g})")
        lines.append(f"mi_selectlabel({label_r:g}, {label_z:g})")
        lines.append(
            f'mi_setblockprop("Ferrite", 0, {mesh_size_mm * 3:g}, "", 0, 0, 0)'
        )
        lines.append("mi_clearselected()")

    # Conductors: one rectangle per turn at its equivalent radius.
    board_bottom = -transformer.stackup.total_thickness_m * 1e3 / 2.0
    for copper in sorted(transformer.stackup.copper, key=lambda c: c.index):
        if not copper.is_copper_winding:
            continue
        circuit = copper.winding
        if circuit not in excitation:
            continue
        z0 = board_bottom + copper.z_m * 1e3
        z1 = z0 + copper.thickness_m * 1e3
        for turn in transformer.turns_on(copper.index):
            r_eq = equivalent_radius(transformer, turn) * 1e3
            w_mm = turn.width_m * 1e3
            r0, r1 = r_eq - w_mm / 2.0, r_eq + w_mm / 2.0
            if r0 <= 0.05:
                continue
            rect(r0, z0, r1, z1)
            lines.append(f"mi_addblocklabel({(r0 + r1) / 2:g}, {(z0 + z1) / 2:g})")
            lines.append(f"mi_selectlabel({(r0 + r1) / 2:g}, {(z0 + z1) / 2:g})")
            lines.append(
                f'mi_setblockprop("Copper", 0, {mesh_size_mm:g}, "{circuit}", '
                "0, 0, 1)"
            )
            lines.append("mi_clearselected()")

    # Air fill.
    lines.append(f"mi_addblocklabel({air_r_mm - 2:g}, {air_z_mm - 2:g})")
    lines.append(f"mi_selectlabel({air_r_mm - 2:g}, {air_z_mm - 2:g})")
    lines.append(
        f'mi_setblockprop("Air", 0, {mesh_size_mm * 8:g}, "", 0, 0, 0)'
    )
    lines.append("mi_clearselected()")

    fem_path = path.with_suffix(".fem")
    lines.append(f'mi_saveas("Z:{fem_path.as_posix()}")')
    lines.append("mi_analyze(1)")
    lines.append("mi_loadsolution()")
    lines.append(f'local h = openfile("Z:{result.as_posix()}", "w")')
    for winding in excitation:
        if frequency_hz > 0:
            # Harmonic mode returns real and imaginary parts, which is what
            # makes R_ac and L separable from one solve.
            lines.append(
                f'local ir, ii, vr, vi, fr, fi = '
                f'mo_getcircuitproperties("{winding}")'
            )
            for label, var in (
                ("current_re", "ir"), ("current_im", "ii"),
                ("volts_re", "vr"), ("volts_im", "vi"),
                ("flux_re", "fr"), ("flux_im", "fi"),
            ):
                lines.append(f'write(h, "{winding}.{label}=", {var}, "\\n")')
        else:
            lines.append(
                f'local ic, vc, fc = mo_getcircuitproperties("{winding}")'
            )
            for label, var in (
                ("current_re", "ic"), ("volts_re", "vc"), ("flux_re", "fc")
            ):
                lines.append(f'write(h, "{winding}.{label}=", {var}, "\\n")')
    lines.append("mo_selectblock(0,0)")
    lines.append('write(h, "energy=", mo_blockintegral(2), "\\n")')
    lines.append("mo_clearblock()")
    lines.append("closefile(h)")
    lines.append("quit()")

    path.write_text("\n".join(lines) + "\n")
    return FemmStudy(
        lua_path=path, result_path=result, frequency_hz=frequency_hz,
        equivalent_radius_m=0.0, unsupported=unsupported_features(),
        mesh_size_mm=mesh_size_mm,
    )
